### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by XJLZ** [purofle/Black-Cat-qqbot#1]
请教，是用什么工具爬取的啊，我用fiddler4， 手机进一些应用就没有网络了，有些应用可以正常联网，请问您是用的什么工具啊？？还是我操作有问题啊。

**Comment by purofle** [comment]
你指的是爬取什么？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月13日(周二) 下午5:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [purofle/Black-Cat-qqbot] 请教 (#1)




 
请教，是用什么工具爬取的啊，我用fiddler4， 手机进一些应用就没有网络了，有些应用可以正常联网，请问您是用的什么工具啊？？还是我操作有问题啊。
 
&mdash;

**Comment by XJLZ** [comment]
> 你指的是爬取什么？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年4月13日(周二) 下午5:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [purofle/Black-Cat-qqbot] 请教 (#1) 请教，是用什么工具爬取的啊，我用fiddler4， 手机进一些应用就没有网络了，有些应用可以正常联网，请问您是用的什么工具啊？？还是我操作有问题啊。 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

比如，酷安酷图，您是通过什么工具或者方式抓包的呢，从而写出这个插件的呢？

**Comment by purofle** [comment]
酷安酷图的酷安api部分使用HttpCanary抓取VirtualXposed内的酷安，token中的X-App-Token使用https://github.com/ZCKun/CoolapkTokenCrack计算


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月14日(周三) 中午1:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [purofle/Black-Cat-qqbot] 请教 (#1)




  
你指的是爬取什么？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年4月13日(周二) 下午5:02 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [purofle/Black-Cat-qqbot] 请教 (#1) 请教，是用什么工具爬取的啊，我用fiddler4， 手机进一些应用就没有网络了，有些应用可以正常联网，请问您是用的什么工具啊？？还是我操作有问题啊。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
比如，酷安酷图，您是通过什么工具或者方式抓包的呢，从而写出这个插件的呢？
 
&mdash;

**Comment by purofle** [comment]
酷安酷图的酷安api部分使用HttpCanary抓取VirtualXposed内的酷安，token中的X-App-Token使用https://github.com/ZCKun/CoolapkTokenCrack计算


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月14日(周三) 中午1:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [purofle/Black-Cat-qqbot] 请教 (#1)




  
你指的是爬取什么？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年4月13日(周二) 下午5:02 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [purofle/Black-Cat-qqbot] 请教 (#1) 请教，是用什么工具爬取的啊，我用fiddler4， 手机进一些应用就没有网络了，有些应用可以正常联网，请问您是用的什么工具啊？？还是我操作有问题啊。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
比如，酷安酷图，您是通过什么工具或者方式抓包的呢，从而写出这个插件的呢？
 
&mdash;
